# Generated by Django 5.2.10 on 2026-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='type_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
