# Generated by Django 5.2.10 on 2026-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_types_type_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='type_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
