# Generated by Django 5.2.10 on 2026-01-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_types_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
