# Generated by Django 5.2.10 on 2026-01-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_types_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nov_img', models.ImageField(blank=True, null=True, upload_to='novel/')),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
