# Generated by Django 5.2.10 on 2026-01-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cat')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
