# Generated by Django 5.2.10 on 2026-01-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.types'),
        ),
        migrations.AddField(
            model_name='novel',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.types'),
        ),
        migrations.AddField(
            model_name='series',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.types'),
        ),
    ]
