# Generated by Django 5.2.10 on 2026-01-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
